#!/usr/bin/env php
<?php declare(strict_types=1);

/**
 * Atmos
 * ---------------------------------------
 * Is a simple library for creating command 
 * line scripts in PHP.
 * 
 * @author  James Levi Crisostomo
 * @version v1.0.4
 * @license http://www.opensource.org/licenses/mit-license.php The MIT License
 */

// Include composer autoload mechanism.
if(file_exists(__DIR__ . '/vendor/autoload.php'))
{
    require __DIR__ . '/vendor/autoload.php';
}

// Initiate command line and pass the arguments from the terminal.
$atmos = \Graphite\Component\Atmos\CommandLine::init($_SERVER['argv'], array(
    'directory'         => __DIR__ . '\\commands',
    'namespace'         => 'Atmos\\Console',
));

// Execute the command line scripts.
$atmos->exec();

// End and terminate the script.
$atmos->end();